name 'scicomp-discourse'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures scicomp-discourse'
long_description 'Installs/Configures scicomp-discourse'
version '0.1.0'
